/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef volatile unsigned int vuint32_t;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

// register address
#define GPIOA_BASE	0x40010800
#define GPIOA_CRL	*(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH	*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR	*(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define RCC_BASE	0x40021000
#define RCC_APB2ENR	*(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR	*(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR	*(volatile uint32_t *)(RCC_BASE + 0x0)
#define AFIO_BASE	0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *)(AFIO_BASE + 0x08)
#define EXTI_BASE	0x40010400
#define EXTI_RTSR	*(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_FTSR	*(volatile uint32_t *)(EXTI_BASE + 0x0C)
#define EXTI_IMR	*(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_PR	*(volatile uint32_t *)(EXTI_BASE + 0x14)
#define NVIC_ISER0	*(volatile uint32_t *)(0xE000E100)





void clock_init(void)
{
	RCC_CFGR |= (0b0110<<18);
	RCC_CFGR |= (0b101<<11);
	RCC_CFGR |= (0b100<<8);
	RCC_CFGR |= (0b10<<0);
	RCC_CR |= 1<<24;
	// INIT CLOCK FOR GPIO
	RCC_APB2ENR |= (1<<2);
	// init clock for AFIO
	RCC_APB2ENR |= 1;
}
void GPIO_init(void)
{
	// PIN13.OUTPUT
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	// PIN0.INPUT
	GPIOA_CRL |= (1<<2);

}
void EXTI_init(void)
{
	AFIO_EXTICR1 |= 0x0;
	//Rising trigger selection
	EXTI_RTSR |= 0x1;
	//Interrupt mask enable
	EXTI_IMR |= 0x1;
	//Enable NVIC IRQ6
	NVIC_ISER0 |= (1<<6);
}



int main(void)
{
	clock_init();
	GPIO_init();
	EXTI_init();

	while(1)
	{
	}
}
extern void EXTI0_IRQHandler()
{
	GPIOA_ODR ^= (1<<13);
	EXTI_PR |= 0x1;
}
