/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
//////////////////////////////
// Eng.TERA
////////////////////////////
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x8.h"
#include "GPIO_DRIVER.h"
#include "USART_DRIVER.h"

uint16_t ch ;

void clock_init()
{
	//GPIOA ,GPIOB & AFIO CLOCK ENABLE
	GPIOA_CLOCK_EN()	;
	GPIOB_CLOCK_EN()	;
	AFIO_CLOCK_EN()	;
	USART1_CLOCK_EN();
}


//interrupt enable
void Usart_callback(interrupts_Bits * IRQ)
{
	MCAL_USART_ReceiveChar(USART1,&ch);
	MCAL_USART_SendChar(USART1,&ch);


}

int main(void)
{
	clock_init();
	//	USART_Config_t USARTCNFG ;
	//	USARTCNFG.baudRate 	=	USART_BAUDRATE_115200	;
	//	USARTCNFG.HWflowCtrl=	USART_HWFlowCtrl_NONE	;
	//	USARTCNFG.IRQ_ENABLE=	USART_IRQ_ENABLE_RXNE	;
	//	USARTCNFG.p_IRQ_CallBAck = IRQCALLBACK	;
	//	USARTCNFG.parity	=USART_PARITY_NONE;
	//	USARTCNFG.payloadLength	=	USART_PAYLOAD_8BIT;
	//	USARTCNFG.stopBits = USART_STOPBITS_ONE	;
	//	USARTCNFG.USART_Mode = USART_MODE_TX_RX;
	//	MCAL_USART_init(USART1, &USARTCNFG);
	//	MCAL_USART_GPIO_SetPins(USART1);

	USART_Config_t UART_CNFG_s;
	UART_CNFG_s.Async_EN = USART_Enable;
	UART_CNFG_s.Async_Config_s.Baud_Rate = 115200;
	UART_CNFG_s.Async_Config_s.Stop_Bits = Stop_1;
	UART_CNFG_s.Async_Config_s.Word_Length =Eight_bits;
	UART_CNFG_s.interrupts_CNFG.RX_Interrupt_Enable_Or_Disable = USART_Enable;
	//	UART_CNFG_s.interrupts_CNFG.TX_Interrupt_Enable_Or_Disable = USART_Disable;
	//	UART_CNFG_s.interrupts_CNFG.TC_Interrupt_Enable_Or_Disable = USART_Disable;
	UART_CNFG_s.CallBack_FN = Usart_callback;
	MCAL_USART_Init(USART1, &UART_CNFG_s);

	MCAL_USART_GPIO_Pins_Config(USART1);

	while (1)
	{




	}
}
