/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//////////////////////////////
// Eng.TERA
////////////////////////////

#include "STM32F103x8.h"
#include "GPIO_DRIVER.h"
#include "EXTI_DRIVER.h"
#include "core_cm3.h"

uint8_t flag,TaskA_flag,TaskB_flag = 0;


#define TaskA_Stack_Size 100 // 100 bytes
#define TaskB_Stack_Size 100 // 100 bytes

extern uint32_t _estack;

//Main Stack
uint32_t _S_MSP = &_estack ;
uint32_t _E_MSP ;


//Process Stack for Task A
uint32_t _S_PSP_TA ;
uint32_t _E_PSP_TA ;

//Process Stack for Task B
uint32_t _S_PSP_TB ;
uint32_t _E_PSP_TB ;

#define OS_SET_PSP(add)						__asm volatile("MSR PSP,%[in0] " : : [in0] "r" (add))
#define OS_SWITCH_SP_to_PSP					__asm volatile("MRS R0,CONTROL \n\t MOV R1,0x02 \n\t ORR R0,R0,R1 \n\t MSR CONTROL,R0")
#define OS_SWITCH_SP_to_MSP					__asm volatile("MRS R0,CONTROL \n\t MOV R1,0x05 \n\t AND R0,R0,R1 \n\t MSR CONTROL,R0")
#define OS_Generate_Exception				__asm volatile("SVC #0x3")
#define Switch_CPU_AccessLevel_Privilege    __asm volatile("MRS R3,CONTROL \n\t LSR R3,R3,#0x1 \n\t LSL R3,R3,#0x1 \n\t MSR CONTROL,R3")
#define Switch_CPU_AccessLevel_Unprivilege  __asm volatile("MRS R3,CONTROL \n\t ORR R3,R3,#0x1 \n\t MSR CONTROL,R3")
//typedef enum{
//
//	Privilege,
//	Unprivilege
//
//}CPUAccessLevel;

//void Switch_CPU_AccessLevel(CPUAccessLevel level)
//{
//	switch(level){
//
//	case Privilege: // Clear bit 0 in CONTROL register
//
//		__asm(  "MRS R3,CONTROL \n\t"
//				"LSR R3,R3,#0x1 \n\t"
//				"LSL R3,R3,#0x1 \n\t"
//				"MSR CONTROL,R3");
//		break;
//
//	case Unprivilege: // Set bit 0 in CONTROL register
//
//
//
//		__asm(  "MRS R3,CONTROL \n\t"
//				"ORR R3,R3,#0x1 \n\t"
//				"MSR CONTROL,R3");
//
//
//
//		break;
//	}
//}


void wait_ms(uint32_t time){
	uint32_t i,j;
	for(i=0; i<time; i++)
		for(j=0; j<255; j++);
}

void PB9_CallBack(){


	if(flag == 0){

		TaskA_flag = 1;
		flag =1;
	}
	else if(flag == 1){

		TaskB_flag = 1;
		flag =0;
	}

}


//void MainOS(void){
//
//	//Main Stack
//	_E_MSP = (_S_MSP - 512) ;
//
//	//Task A
//	_S_PSP_TA = (_E_MSP - 8);
//	_E_PSP_TA = ( _S_PSP_TA - TaskA_Stack_Size ) ;
//
//	//Task B
//	_S_PSP_TB = ( _E_PSP_TA - 8 );
//	_E_PSP_TB = ( _S_PSP_TB - TaskB_Stack_Size );
//
//
//	while(1)
//	{
//		__asm("NOP");
//		if(TaskA_flag == 1)
//		{
//			//Set PSP register to _S_PSP_TA
//			OS_SET_PSP(_S_PSP_TA);
//			//SP -> PSP
//			OS_SWITCH_SP_to_PSP;
//			// Switch from Privileged to Unprivileged
//			Switch_CPU_AccessLevel_Unprivilege;
//
//			TaskA_flag = TaskA(1, 2, 3);
//
//			// Switch from Unprivileged to Privileged
//			OS_Generate_Exception;
//			// SP -> MSP
//			OS_SWITCH_SP_to_MSP;
//
//		}
//		else if (TaskB_flag == 1)
//		{
//			//Set PSP register to _S_PSP_TB
//			OS_SET_PSP(_S_PSP_TB);
//			//SP -> PSP
//			OS_SWITCH_SP_to_PSP;
//			// Switch from Privileged to Unprivileged
//			Switch_CPU_AccessLevel_Unprivilege;
//
//			TaskB_flag = TaskB(1, 2, 3, 4);
//
//			// Switch from Unprivileged to Privileged
//			OS_Generate_Exception;
//			// SP -> MSP
//			OS_SWITCH_SP_to_MSP;
//
//
//
//		}
//
//
//	}
//
//}
//
int OS_SVC_Set(int a,int b,int SVC_ID)
{
	int result;

	switch(SVC_ID)
	{
	case 1: //add
		__asm("svc #0x01");
		break;
	case 2: //sub
		__asm("svc #0x02");
		break;
	case 3: // MULT
		__asm("svc #0x03");
		break;
	case 4: //PendSV
		SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk;
		break;

	}
	__asm("MOV %[out0],R0": [out0] "=r" (result));
	return result;
}
void OS_SVC_services(int * StackFramePointer)
{
	//OS_SVC_Set Stack -> R0 -> argument 0 = StackFramePointer
	//OS_SVC_Set Stack : R0,R1,R2,R3,R12,LR,PC,xPSR
	unsigned char SVC_Number;
	unsigned int val1,val2;

	SVC_Number =  *((unsigned char*)( ( (unsigned char*)StackFramePointer[6] ) - 2 )) ;

	val1 = StackFramePointer[0];
	val2 = StackFramePointer[1];

	switch(SVC_Number)
	{
	case 1: // ADD
		StackFramePointer[0]= val1 + val2 ;
		break;
	case 2: //SUB
		StackFramePointer[0]= val1 - val2 ;
		break;
	case 3: // MULT
		StackFramePointer[0]= val1 * val2 ;
		break;
	}

	return;




}
__attribute ((naked)) void SVC_Handler(void)
{
	__asm("TST LR,0x4");
	__asm("ITE EQ");
	__asm("MRSEQ R0,MSP");
	__asm("MRSNE R0,PSP");
	__asm("B OS_SVC_services");



}
void PendSV_Handler(void)
{

}

int main(void){


	//	// Enable clock
	//	GPIOA_CLOCK_EN();
	//	GPIOB_CLOCK_EN();
	//	AFIO_CLOCK_EN();
	//
	//	EXTI_Config_t EXTI_CFG;
	//	EXTI_CFG.EXTI_GPIO_Mapping = PB9_EXTI9;
	//	EXTI_CFG.Rising_or_Falling = FALLING;
	//	EXTI_CFG.Function_call = PB9_CallBack;
	//	MCAL_EXTI_init(&EXTI_CFG);
	//

	//	MainOS();
	flag =1;
	flag = OS_SVC_Set(3, 3, 1); // ADD
	flag = OS_SVC_Set(3, 3, 2); // SUB
	flag = OS_SVC_Set(3, 3, 3); // MULT
	flag = OS_SVC_Set(0, 0, 4); // PendSV





	while(1)
	{
		if(flag)
		{
			flag=0;
		}
	}

}
