/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "GPIO_DRIVER.h"





void clock_init(void)
{
	// INIT CLOCK FOR GPIO
	GPIOA_CLOCK_EN();
	GPIOB_CLOCK_EN();

}
void GPIO_init(void)
{
	//port A pin1 input floating register
	//00: Input mode (reset state)
	//01: Floating input (reset state)
	Pin_Config_t PA_1_input;
	PA_1_input.input=1;
	PA_1_input.mode= Input_floating;
	PA_1_input.Pin_Num=1;
	MCAL_GPIO_Init(GPIOA, &PA_1_input);


	//port A pin13 input floating register
	//00: Input mode (reset state)
	//01: Floating input (reset state)
	Pin_Config_t PA_13_input;
	PA_13_input.input=1;
	PA_13_input.mode= Input_floating;
	PA_13_input.Pin_Num=13;
	MCAL_GPIO_Init(GPIOA, &PA_13_input);


	//===========================

	//port B pin1 output Open-drain mode
	//01: Output mode, max speed 10 MHz
	//01: General purpose output Open-drain
	Pin_Config_t PB_1_output;
	PB_1_output.GPIO_output=1;
	PB_1_output.mode= Output_Open_drain;
	PB_1_output.Speed_Output=speed_10;
	PB_1_output.Pin_Num=1;
	MCAL_GPIO_Init(GPIOB, &PB_1_output);


	//port B pin13 output Open-drain mode
	//01: Output mode, max speed 10 MHz
	//01: General purpose output Open-drain
	Pin_Config_t PB_13_output;
	PB_13_output.GPIO_output=1;
	PB_13_output.mode= Output_Open_drain;
	PB_13_output.Speed_Output=speed_10;
	PB_13_output.Pin_Num=13;
	MCAL_GPIO_Init(GPIOB, &PB_13_output);

}
void delay()
{
	unsigned int i;
	for(i =0; i< 1000; i++);
}


int main(void)
{
	clock_init();
	GPIO_init();
	MCAL_GPIO_WritePin(GPIOB, 1, 1);
	MCAL_GPIO_WritePin(GPIOB, 13, 1);
	while(1)
	{
		if(MCAL_GPIO_ReadPin(GPIOA, 1) == 0)
		{
			MCAL_GPIO_TogglePin(GPIOB, 1);
			while(MCAL_GPIO_ReadPin(GPIOA, 1) == 0);// single pressing
		}
		if(MCAL_GPIO_ReadPin(GPIOA, 13) == 1)// multiple pressing
		{
			MCAL_GPIO_TogglePin(GPIOB, 13);
		}

		delay();

	}
}
